USE MASTER
IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME='DBSISTORE')
DROP DATABASE DBSISTORE
GO
CREATE DATABASE DBSISTORE
ON PRIMARY (NAME='DBSISTORE.MDF',FILENAME='D:\Programas_Ozblu\Desarrollo\CODE\Escritorio\SISTORE\Database\DBSISTORE.MDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
LOG ON (NAME='DBSISTORE_LOG.LDF',FILENAME='D:\Programas_Ozblu\Desarrollo\CODE\Escritorio\SISTORE\Database\DBSISTORE_LOG.LDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
