USE MASTER
DROP DATABASE FINADB
GO
CREATE DATABASE FINADB
ON PRIMARY (NAME='FINADB.MDF',FILENAME='D:\Programas_Ozblu\Desarrollo\CODE\Escritorio\Fina\Database\FINADB.MDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
LOG ON (NAME='FINADB_LOG.LDF',FILENAME='D:\Programas_Ozblu\Desarrollo\CODE\Escritorio\Fina\Database\FINADB_LOG.LDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
