USE MASTER
IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME='DBSISTORE')
DROP DATABASE DBSISTORE
GO
CREATE DATABASE DBSISTORE
ON PRIMARY (NAME='DBSISTORE.MDF',FILENAME='D:\Database\DBSISTORE.MDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
LOG ON (NAME='DBSISTORE_LOG.LDF',FILENAME='D:\Database\DBSISTORE_LOG.LDF',SIZE=5MB,MAXSIZE=10GB,FILEGROWTH=10%)
GO

USE DBSISTORE
GO

CREATE TABLE  TTABLA (
  IDTABLA CHAR(3) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
  )
  GO

CREATE TABLE TABLADETALLE (
  IDTABLADETALLE CHAR(6) NOT NULL PRIMARY KEY,
  IDTABLA CHAR(3) DEFAULT NULL,
  DESCRIPCION VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO

ALTER TABLE TABLADETALLE ADD CONSTRAINT FK_TABLADETALLE_IDTABLA FOREIGN KEY (IDTABLA) REFERENCES TTABLA (IDTABLA)
GO

CREATE TABLE TTIENDA (
  IDTIENDA INT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
  NOMBRE VARCHAR(100) DEFAULT NULL,
  DIRECCION VARCHAR(100) DEFAULT NULL,
  DEPARTAMENTO VARCHAR(45) DEFAULT NULL,
  PROVINCIA VARCHAR(45) DEFAULT NULL,
  DISTRITO VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL
) 
GO

CREATE TABLE TALMACEN (
IDALMACEN INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  DESCRIPCION VARCHAR(100) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  IDTIENDA INT NOT NULL
) 
GO

ALTER TABLE TALMACEN
ADD CONSTRAINT FK_TALMACEN_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TCATEGORIA (
  IDCATEGORIA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  DESCRIPCION VARCHAR(100) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  DIARETIRO INT DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL
) 
GO

CREATE TABLE TPROVEEDOR (
  IDPROVEEDOR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  RUC VARCHAR(12) DEFAULT NULL,
  RAZONSOCIAL VARCHAR(100) DEFAULT NULL,
  DIRECCION VARCHAR(100) DEFAULT NULL,
  TELEFONO VARCHAR(15) DEFAULT NULL,
  RUBRO VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL
) 
GO

ALTER TABLE TPROVEEDOR
ADD CONSTRAINT FK_TPROVEEDOR_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TMOVIMIENTO (
  IDMOVIMIENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDTIENDA INT NOT NULL,
  CODOPERACION CHAR(6) DEFAULT NULL,
  IDPROVEEDOR INT DEFAULT NULL,
  MONTOTOTAL FLOAT DEFAULT NULL,
  FCHMOV DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  CODESTADO CHAR(6) DEFAULT NULL
)
GO

ALTER TABLE TMOVIMIENTO ADD CONSTRAINT TMOVIMIENTO_IDPROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES TPROVEEDOR (IDPROVEEDOR)
ALTER TABLE TMOVIMIENTO ADD CONSTRAINT TMOVIMIENTO_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TPRODUCTO (
  IDPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  CODUME CHAR(6) DEFAULT NULL,
  CODGRUPO CHAR(6) DEFAULT NULL,
  EAN VARCHAR(15) DEFAULT NULL,
  DESCRIPCION VARCHAR(100) DEFAULT NULL,
  PRECIO FLOAT DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  IDCATEGORIA INT DEFAULT NULL
)
GO

ALTER TABLE TPRODUCTO ADD CONSTRAINT FK_TPRODUCTO_IDCATEGORIA FOREIGN KEY (IDCATEGORIA) REFERENCES TCATEGORIA (IDCATEGORIA)
GO

CREATE TABLE TMOVIMIENTODETALLE (
IDMOVIMIENTODETALLE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDMOVIMIENTO INT DEFAULT NULL,
  IDPRODUCTO INT DEFAULT NULL,
  CANTIDAD CHAR(18) DEFAULT NULL,
  FECHVEN DATETIME DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO

ALTER TABLE TMOVIMIENTODETALLE ADD CONSTRAINT FK_TMOVIMIENTODETALLE_IDMOVIMIENTO FOREIGN KEY (IDMOVIMIENTO) REFERENCES TMOVIMIENTO (IDMOVIMIENTO)
ALTER TABLE TMOVIMIENTODETALLE ADD CONSTRAINT TMOVIMIENTODETALLE_IDPRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES TPRODUCTO (IDPRODUCTO)


CREATE TABLE TDEPOSITO (
IDDEPOSITO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDPRODUCTO INT DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  IDALMACEN INT DEFAULT NULL,
  CANTIDAD FLOAT DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHRET DATETIME DEFAULT NULL
) 
GO

ALTER TABLE TDEPOSITO ADD CONSTRAINT FK_TDEPOSITO_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
ALTER TABLE TDEPOSITO ADD CONSTRAINT FK_TDEPOSITO_IDPRODUCTO FOREIGN KEY (IDPRODUCTO) REFERENCES TPRODUCTO (IDPRODUCTO)
ALTER TABLE TDEPOSITO ADD CONSTRAINT FK_TDEPOSITO_IDALMACEN FOREIGN KEY (IDALMACEN) REFERENCES TALMACEN (IDALMACEN)
GO

CREATE TABLE TUSUARIO (
  IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  TIPO CHAR(6) DEFAULT NULL,
  USUARIO VARCHAR(45) DEFAULT NULL,
  CLAVE VARCHAR(100) DEFAULT NULL,
  EMAIL VARCHAR(45) DEFAULT NULL,
  NOMBRES VARCHAR(45) DEFAULT NULL,
  APELLIDOS VARCHAR(45) DEFAULT NULL,
  FCHNAC DATETIME DEFAULT NULL,
  DNI VARCHAR(9) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL
) 
GO

ALTER TABLE TUSUARIO ADD CONSTRAINT FK_TUSUARIO_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TOPCIONES (
  IDOPCIONES INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  DESCRIPCION VARCHAR(45) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  ORDEN INT DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 

ALTER TABLE TOPCIONES ADD CONSTRAINT FK_TOPCIONES_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TPERFILES (
  IDPERFIL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  DESCRIPCION VARCHAR(45) DEFAULT NULL,
  IDTIENDA INT DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO

ALTER TABLE TPERFILES ADD CONSTRAINT FK_TPERFILES_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA)
GO

CREATE TABLE TPERFIL_OPCIONES (
  IDREGISTRO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDPERFIL INT DEFAULT NULL,
  IDOPCIONES INT DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO

ALTER TABLE TPERFIL_OPCIONES ADD CONSTRAINT FK_TPERFIL_OPCIONES_IDOPCIONES FOREIGN KEY (IDOPCIONES) REFERENCES TOPCIONES (IDOPCIONES)
ALTER TABLE TPERFIL_OPCIONES ADD CONSTRAINT FK_TPERFIL_OPCIONES_IDPERFIL FOREIGN KEY (IDPERFIL) REFERENCES TPERFILES (IDPERFIL)
GO

CREATE TABLE TPERFIL_USUARIO (
  IDREGISTRO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDUSUARIO INT DEFAULT NULL,
  IDPERFIL INT DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO

ALTER TABLE TPERFIL_USUARIO ADD CONSTRAINT FK_TPERFIL_USUARIO_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES TUSUARIO (IDUSUARIO)
ALTER TABLE TPERFIL_USUARIO ADD CONSTRAINT FK_TPERFIL_USUARIO_IDPERFIL FOREIGN KEY (IDPERFIL) REFERENCES TPERFILES (IDPERFIL)
GO

CREATE TABLE TSUCURSAL (
  IDSUCURSAL INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDTIENDA INT NOT NULL,
  DESCRIPCION VARCHAR(100) DEFAULT NULL,
  DIRECCION VARCHAR(100) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHMOD DATE DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
GO
ALTER TABLE TSUCURSAL ADD CONSTRAINT FK_TSUCURSAL_IDTIENDA FOREIGN KEY (IDTIENDA) REFERENCES TTIENDA (IDTIENDA);
GO

CREATE TABLE TUSUARIO_SUCURSAL (
  IDREGISTRO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDUSUARIO INT DEFAULT NULL,
  IDSUCURSAL INT DEFAULT NULL,
  USRCREA VARCHAR(45) DEFAULT NULL,
  FCHCREA DATETIME DEFAULT NULL,
  USRMOD VARCHAR(45) DEFAULT NULL,
  FCHMOD DATETIME DEFAULT NULL,
  FLGELI CHAR(1) DEFAULT NULL
) 
ALTER TABLE TUSUARIO_SUCURSAL ADD CONSTRAINT FK_TUSUARIO_SUCURSAL_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES TUSUARIO (IDUSUARIO)
ALTER TABLE TUSUARIO_SUCURSAL ADD CONSTRAINT FK_TUSUARIO_SUCURSAL_IDSUCURSAL FOREIGN KEY (IDSUCURSAL) REFERENCES TSUCURSAL (IDSUCURSAL)
