SELECT*FROM TPERFILES
SELECT*FROM TOPCIONES
SELECT*FROM TPERFIL_OPCIONES
SELECT*FROM TPERFIL_USUARIO

--ALMACEN
INSERT INTO TOPCIONES VALUES ('ALMACEN','LISTADO DE STOCK','CONSULTA','0')
INSERT INTO TOPCIONES VALUES ('ALMACEN','MOVIMIENTOS','ALMACEN','0')

--PRODUCTOS
INSERT INTO TOPCIONES VALUES ('ALMACEN','PRODUCTOS','ALMACEN','0')

--PROVEEDORES
INSERT INTO TOPCIONES VALUES ('ALMACEN','PROVEEDORES','ALMACEN','0')

--USUARIOS
INSERT INTO TOPCIONES VALUES ('TI','USUARIOS','USUARIOS','0')
INSERT INTO TOPCIONES VALUES ('TI','REESTABLECER CLAVE USUARIO','USUARIOS','0')

SELECT*FROM TPERFIL_OPCIONES
INSERT INTO  TPERFIL_OPCIONES VALUES ('1','5','0','0','0','0','0','0')
INSERT INTO  TPERFIL_OPCIONES VALUES ('1','6','0','0','0','0','0','0')

INSERT INTO  TPERFIL_OPCIONES VALUES ('2','1','0','0','0','0','0','0')
INSERT INTO  TPERFIL_OPCIONES VALUES ('2','2','0','0','0','0','0','0')
INSERT INTO  TPERFIL_OPCIONES VALUES ('2','3','0','0','0','0','0','0')
INSERT INTO  TPERFIL_OPCIONES VALUES ('2','4','0','0','0','0','0','0')

INSERT INTO  TPERFIL_OPCIONES VALUES ('3','2','0','0','1','0','0','0')
INSERT INTO  TPERFIL_OPCIONES VALUES ('3','3','0','0','1','0','0','0')

INSERT INTO  TPERFIL_OPCIONES VALUES ('4','1','0','1','1','1','0','0')

SELECT TOPA.DESCRIPCION,TOPA.GRUPO,TOPA.MODULO,TOPC.LEER,TOPC.MODIFICAR,TOPC.CREAR,TOPC.IMPRIMIR,TOPC.EXPORTAR
 FROM TUSUARIO U INNER JOIN (TPERFIL_USUARIO TU INNER JOIN (TPERFIL_OPCIONES TOPC INNER JOIN TOPCIONES TOPA ON TOPC.IDOPCIONES=TOPA.IDOPCIONES)ON TU.IDPERFIL_USUARIO=TOPC.IDPERFIL_USUARIO) ON U.IDUSUARIO=TU.IDUSUARIO
 WHERE U.IDUSUARIO='4' AND TOPA.FLGELI='0'

SELECT*FROM TUSUARIO











