use DBSISTORE
SELECT * FROM TTABLA
INSERT INTO TTABLA SELECT ('001','TIPO_USUARIO',NOW(),'ADMIN','0')
INSERT INTO TTABLA VALUES ('002','UME',NOW(),'ADMIN','0')
INSERT INTO TTABLA VALUES ('003','OPERACION',NOW(),'ADMIN','0')
INSERT INTO TTABLA VALUES ('004','ESTADO',NOW(),'ADMIN','0')

SELECT * FROM TABLADETALLE
INSERT INTO TABLADETALLE SELECT ('001001','001','ADMIN',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('001002','001','USUARIO',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('002001','002','UN',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('002002','002','CAJ',NOW(),'MASTER',NOW(),'MASTER','0')

INSERT INTO TABLADETALLE VALUES ('003001','003','SALIDA',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('003002','003','INGRESO',NOW(),'MASTER',NOW(),'MASTER','0')

INSERT INTO TABLADETALLE VALUES ('004001','004','CREADO',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('004002','004','MODIFICADO',NOW(),'MASTER',NOW(),'MASTER','0')
INSERT INTO TABLADETALLE VALUES ('004003','004','GUARDADO',NOW(),'MASTER',NOW(),'MASTER','0')

SELECT * FROM TTIENDA
INSERT INTO TTIENDA SELECT ('MASTI CENTER','ICABOTS','ICA','ICA','ICA',NOW(),'ADMIN',NOW(),'ADMIN','0')

SELECT * FROM TSUCURSAL
INSERT INTO TSUCURSAL SELECT ('1','CHINCHA','AV. BENAVIDES 530',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TSUCURSAL VALUES ('1','PISCO','AV. LOS OLIVOS 530',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TSUCURSAL VALUES ('1','ICA','AV. LOS HUACACHINA 530',NOW(),'ADMIN',NOW(),'ADMIN','0')

SELECT * FROM TUSUARIO
INSERT INTO TUSUARIO SELECT ('001001','KEVIN.FLORES','123','KEVIN.FLORES@GG.COM','KEVIN','FLORES','07/01/1997','72793128',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TUSUARIO VALUES ('001001','ANDERS.ROMERO','123','ANDERS.ROMERO@GG.COM','ANDERS','ROMERO','07/01/1997','72793128',NOW(),'ADMIN',NOW(),'ADMIN','0')

SELECT * FROM TSUCURSAL_USUARIO
INSERT INTO TSUCURSAL_USUARIO SELECT ('1','2',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TSUCURSAL_USUARIO VALUES ('2','2',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TSUCURSAL_USUARIO VALUES ('3','1',NOW(),'ADMIN',NOW(),'ADMIN','0')


SELECT T.IDSUCURSAL,USUARIO,DESCRIPCION AS TIENDA, T.FLGELI FROM TSUCURSAL T INNER JOIN
 TSUCURSAL_USUARIO TSU ON T.IDSUCURSAL=TSU.IDSUCURSAL INNER JOIN TUSUARIO TU ON TSU.IDUSUARIO=TU.IDUSUARIO WHERE T.FLGELI='0'

SELECT *FROM TALMACEN
INSERT INTO TALMACEN SELECT ('1','FRIO PISCO',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TALMACEN VALUES ('1','ALMACEN 1 PISCO',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TALMACEN VALUES ('2','ALMACEN 1 CHINCHA',NOW(),'ADMIN',NOW(),'ADMIN','0')

SELECT * FROM TCATEGORIA
INSERT INTO TCATEGORIA SELECT ('LECHE','15',NOW(),'ADMIN',NOW(),'ADMIN')
INSERT INTO TCATEGORIA VALUES ('GASEOSAS','15',NOW(),'ADMIN',NOW(),'ADMIN')

SELECT * FROM TPRODUCTO
INSERT INTO TPRODUCTO SELECT ('1','002001','775757575','LECHE ENTERA GLORIA 400GR','3.10',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TPRODUCTO VALUES ('1','002001','775757572','LECHE LIGTH GLORIA 400GR','3.10',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TPRODUCTO VALUES ('1','002001','775757573','LECHE ULTRALIGTH GLORIA 400GR','3.10',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TPRODUCTO VALUES ('1','002002','775757574','GASEOSA GUARANA 3LT','9.10',NOW(),'ADMIN',NOW(),'ADMIN','0')

SELECT * FROM TPROVEEDOR
INSERT INTO TPROVEEDOR SELECT ('10407374334','DATEC S.A.C','CALLE ALFONSO UGARTE 532','5555-5555','PRODUCTOS GENERALES',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TPROVEEDOR VALUES ('10407374334','LINDLEY CORPORATION S.A','CALLE LIMA 532','5555-5555','GASEOSAS',NOW(),'ADMIN',NOW(),'ADMIN','0')

USE DBSISTORE

SELECT*FROM TALMACEN
SELECT*FROM TMOVIMIENTO
SELECT*FROM TABLADETALLE
INSERT INTO TMOVIMIENTO SELECT ('1','2','003002','0.0',NOW(),'ADMIN','0','004001')
-- ESTADO CREADO

SELECT*FROM TPRODUCTO
SELECT*FROM TMOVIMIENTODETALLE
INSERT INTO TMOVIMIENTODETALLE SELECT ('1','1','100','02/05/2020',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TMOVIMIENTODETALLE VALUES ('1','2','24','01/05/2020',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TMOVIMIENTODETALLE VALUES ('1','3','48','02/05/2020',NOW(),'ADMIN',NOW(),'ADMIN','0')
INSERT INTO TMOVIMIENTODETALLE VALUES ('1','4','120','01/05/2020',NOW(),'ADMIN',NOW(),'ADMIN','0')
-- ESTADO MODIFICADO

SELECT*FROM TDEPOSITO

INSERT INTO TDEPOSITO (IDPRODUCTO,IDALMACEN,CANTIDAD,FCHCREA,USRCREA,FCHMOD,USRMOD,FCHVEN,FCHRET) 
SELECT MD.IDPRODUCTO,M.IDALMACEN,MD.CANTIDAD,NOW() AS FCHCREA,'ADMIN' AS USRCREA,NOW()
 AS FCHMOD,'ADMIN' AS USRMOD, MD.FECHVEN,MD.FECHVEN+C.DIARETIRO AS FECHA_RETIRO FROM TMOVIMIENTO
  M INNER JOIN (TMOVIMIENTODETALLE MD INNER JOIN (TPRODUCTO P INNER JOIN TCATEGORIA C ON 
  P.IDCATEGORIA=C.IDCATEGORIA) ON MD.IDPRODUCTO=P.IDPRODUCTO) ON M.IDMOVIMIENTO=MD.IDMOVIMIENTO WHERE M.IDMOVIMIENTO='1'

UPDATE TMOVIMIENTO SET CODESTADO='004003', FLGELI='1' WHERE IDMOVIMIENTO='1'
UPDATE TMOVIMIENTODETALLE SET FLGELI='1' WHERE IDMOVIMIENTO='1'
-- ESTADO GUARDADO

SELECT * FROM TALMACEN
SELECT * FROM TPRODUCTO
SELECT * FROM TTABLA
SELECT * FROM TABLADETALLE
SELECT * FROM TDEPOSITO
SELECT * FROM TUSUARIO
SELECT * FROM TMOVIMIENTO
SELECT * FROM TTIENDA
SELECT * FROM TMOVIMIENTODETALLE
SELECT * FROM TSUCURSAL
SELECT * FROM TSUCURSAL_USUARIO
SELECT * FROM TCATEGORIA
SELECT * FROM TPROVEEDOR
SELECT * FROM TPERFILES
SELECT * FROM TPERFIL_USUARIO
SELECT * FROM TOPCIONES
SELECT * FROM TPERFIL_OPCIONES