USE FINADB
GO
CREATE TABLE TESTADO(
CODESTADO	int PRIMARY KEY IDENTITY(1,1),
DETALLE	varchar(50),
TABLA	varchar(50)
)
GO


CREATE TABLE TUME(
CODUME	int PRIMARY KEY,
DETALLE	varchar(50)
)
GO

CREATE TABLE TGRUPO(
CODGRUPO	int PRIMARY KEY,
DETALLE	varchar(100),
DIARETIRO	int
)
GO

CREATE TABLE TTIENDA(
CODTIENDA	INT PRIMARY KEY,
NOMBRE	varchar(100),
DIRECCION	varchar(100),
DEPARTAMENTO	varchar(50),
PROVINCIA	varchar(50),
DISTRITO	varchar(50)
)
GO

CREATE TABLE TALMACEN(
CODALMACEN	INT PRIMARY KEY,
DESCRIPCION	varchar(50),
)
GO

CREATE TABLE TUSUARIO(
CODUSUARIO	int PRIMARY KEY IDENTITY(1,1),
CODESTADO	int,
CATEGORIA	varchar(10),
USUARIO	varchar(50),
CLAVE	varchar(50),
EMAIL	varchar(50),
NOMBRE	varchar(100),
APELLIDOS	varchar(100),
FECHANAC	DATE,
DNI	varchar(10),
CONSTRAINT  FK_CODESTADO_USUARIO FOREIGN KEY(CODESTADO) REFERENCES TESTADO(CODESTADO)
)
GO

CREATE TABLE TPROVEDOR(
RUC	int PRIMARY KEY,
RAZONSOCIAL	varchar(100),
DIRECCION	varchar(100),
TELEFONO	varchar(100),
RUBRO	varchar(50),
CODESTADO	int,
CONSTRAINT  FK_CODESTADO_PROVEDOR FOREIGN KEY(CODESTADO) REFERENCES TESTADO(CODESTADO)
)
GO

CREATE TABLE TPRODUCTO(
CODPROD	int PRIMARY KEY IDENTITY(10000,1),
CODUME	INT,
CODGRUPO	INT,
CODESTADO	int,
EAN13	varchar(15),
DESCRIPCION	varchar(100),
PRECIO	float,
CONSTRAINT  FK_CODUME_PRODUCTO FOREIGN KEY(CODUME) REFERENCES TUME(CODUME),
CONSTRAINT  FK_CODGRUPO_PRODUCTO FOREIGN KEY(CODGRUPO) REFERENCES TGRUPO(CODGRUPO),
CONSTRAINT  FK_CODESTADO_PRODUCTO FOREIGN KEY(CODESTADO) REFERENCES TESTADO(CODESTADO)
)
GO

CREATE TABLE TOPERACION(
CODOPERACION INT PRIMARY KEY IDENTITY(1,1),
DETALLE VARCHAR(50)
)

CREATE TABLE TMOVIMIENTO(
CODMOVIMIENTO int PRIMARY KEY IDENTITY(1,1),
CODUSUARIO	int,
CODESTADO int,
CODOPERACION int,
RUC	int,
MONTOTOTAL float,
FECHA_MOV date,
CONSTRAINT  FK_CODOPERACION_MOV FOREIGN KEY(CODOPERACION) REFERENCES TOPERACION(CODOPERACION),
CONSTRAINT  FK_CODESTADO_MOV FOREIGN KEY(CODESTADO) REFERENCES TESTADO(CODESTADO),
CONSTRAINT  FK_CODUSUARIO_MOV FOREIGN KEY(CODUSUARIO) REFERENCES TUSUARIO(CODUSUARIO),
CONSTRAINT  FK_RUC_MOV FOREIGN KEY(RUC) REFERENCES TPROVEDOR(RUC)
)
GO

CREATE TABLE TDETMOVIMIENTO(
CODMOVIMIENTO int,
CODPROD	INT,
CANTIDAD	float,
FECHAVEN	date,
CONSTRAINT  FK_CODINGRESO_DETMOV FOREIGN KEY(CODMOVIMIENTO) REFERENCES TMOVIMIENTO(CODMOVIMIENTO),
CONSTRAINT  FK_CODPROD_DETMOV FOREIGN KEY(CODPROD) REFERENCES TPRODUCTO(CODPROD)
)
GO
CREATE TABLE TDEPOSITO(
CODPROD	INT,
CODALMACEN	INT,
CODTIENDA	INT,
CANTIDAD	float,
FECHA_VEN	date,
FECHA_RET	date,
CONSTRAINT  FK_CODPROD_TDEPOSITO FOREIGN KEY(CODPROD) REFERENCES TPRODUCTO(CODPROD),
CONSTRAINT  FK_CODALMACEN_TDEPOSITO FOREIGN KEY(CODALMACEN) REFERENCES TALMACEN(CODALMACEN),
CONSTRAINT  FK_CODTIENDA_TDEPOSITO FOREIGN KEY(CODTIENDA) REFERENCES TTIENDA(CODTIENDA)
)
GO

/*
----POR AGREGAR
Modulo inventarios
Modulo de cajas
Modulo de RRHH
*/