USE DBSISTORE
GO
CREATE TABLE TTABLA(
IDTABLA	CHAR(6) PRIMARY KEY,
DESCRIPCION	varchar(100),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FLGELI CHAR(1)
)
GO

CREATE TABLE TTABLADETALLE(
IDTABLADETALLE	CHAR(6) PRIMARY KEY,
IDTABLA	CHAR(6),
DETALLE	varchar(50),
DESCRIPCION	varchar(100),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FCHMOD DATETIME,
USRMOD VARCHAR(45),
FLGELI CHAR(1)
)
GO


CREATE TABLE TPRODUCTO(
IDPRODUCTO	int PRIMARY KEY IDENTITY(1000,1),
CODUME	CHAR(6),
EAN VARCHAR(15),
DESCRIPCION	varchar(100),
PRECIO	float,
FLGELI CHAR(1),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FCHMOD DATETIME,
USRMOD VARCHAR(45),
IDCATEGORIA INT
)
GO

CREATE TABLE TCATEGORIA(
IDCATEGORIA	int PRIMARY KEY,
DESCRIPCION	varchar(100),
DIARETIRO INT,
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FCHMOD DATETIME,
USRMOD VARCHAR(45),
FLGELI CHAR(1)
)
GO

CREATE TABLE TDEPOSITO(
IDDEPOSITO INT PRIMARY KEY IDENTITY(1,1),
IDDPRODUCTO	INT,
CANTIDAD	float,
FCHCREA DATETIME,
USRCREA varchar(45),
FCHMOD DATETIME,
USRMOD varchar(45),
FCHRET DATETIME,
IDSUCURSAL INT
)
GO

CREATE TABLE TTIENDA(
IDTIENDA	INT PRIMARY KEY,
NOMBRE	varchar(100),
DIRECCION	varchar(100),
DEPARTAMENTO	varchar(50),
PROVINCIA	varchar(50),
DISTRITO	varchar(50),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FCHMOD DATETIME,
USRMOD varchar(45),
FLGELI CHAR(1)
)
GO

CREATE TABLE TUSUARIO(
IDUSUARIO	int PRIMARY KEY IDENTITY(1000,1),
TIPO	CHAR(6),
USUARIO	varchar(45),
CLAVE	varchar(100),
EMAIL	varchar(45),
NOMBRES	varchar(45),
APELLIDOS	varchar(45),
FCHNAC	DATE,
DNI	varchar(9),
FLGELI CHAR(1),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
IDTIENDA INT,
FECHAMOD DATETIME,
USRMOD VARCHAR(45)
)
GO

CREATE TABLE TALMACEN(
IDALMACEN	INT PRIMARY KEY,
DESCRIPCION	varchar(100),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FLGELI CHAR(1),
FCHMOD DATETIME,
USRMOD VARCHAR(45),
IDTIENDA INT
)
GO

CREATE TABLE TPROVEEDOR(
IDPROVEEDOR INT PRIMARY KEY IDENTITY(1000,1),
RUC	VARCHAR(12),
RAZONSOCIAL	varchar(100),
DIRECCION	varchar(100),
TELEFONO	varchar(15),
RUBRO VARCHAR(45),
FLGELI CHAR(1),
IDTIENDA INT,
FCHCREA DATETIME,
USRCREA varchar(45),
FCHMOD DATETIME,
USRMOD varchar(45)
)
GO


-- TESTADO, TUME, TOPERACION



--------------------------------


CREATE TABLE TMOVIMIENTO(
IDMOVIMIENTO int PRIMARY KEY IDENTITY(5000000,1),
CODOPERACION VARCHAR(6),
IDPROVEEDOR INT,
MONTOTOTAL float,
FCHMOV dateTIME,
USRCREA varchar(50),
FLGELIMINADO CHAR(1),
IDTIENDA INT
)
GO

CREATE TABLE TMOVIMIENTODETALLE(
IDMOVIMIENTODETALLE int PRIMARY KEY IDENTITY(1,1),
IDMOVIMIENTO int,
IDPRODUCTO	INT,
CANTIDAD	char(18),
FECHVEN	DATETIME,
FCHCREA DATETIME,
USRCREA varchar(45),
FCHMOD DATETIME,
USRMOD varchar(45),
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TSUCURSAL(
IDSUCURSAL INT,
IDTIENDA INT,
DESCRIPCION VARCHAR(100),
DIRECCION VARCHAR(100),
FCHCREA DATETIME,
USRCREA VARCHAR(45),
FCHMOD DATETIME,
USRMOD VARCHAR(45),
FLGELI CHAR(1)
)

CREATE TABLE TUSARIO_SUCURSAL(
IDREGISTRO CHAR(18),
IDUSUAURIO INT,
IDSUCURSAL INT,
USRCREA VARCHAR(45),
FCHCREA DATETIME,
USRMOD VARCHAR(45),
FCHMOD DATETIME,
FLGELI CHAR(1)
)

CREATE TABLE TPERFILES (
IDPERFIL INT,
DESCRIPCION VARCHAR(45),
IDTIENDA INT,
USRCREA VARCHAR(45),
FCHCREA DATETIME,
USRMOD VARCHAR(45),
FCHMOD DATETIME,
FLGELI CHAR(1)
)

CREATE TABLE TPERFIL_OPCIONES(
IDREGISTRO CHAR(18),
IDOPCIONES INT,
USRCREA VARCHAR(45),
FCHCREA DATETIME,
USRMOD VARCHAR(45),
FCHMOD DATETIME,
FLGELI CHAR(1)
)

CREATE TABLE TOPCIONES(
IDOPCIONES INT,
DESCRIPCION VARCHAR(45),
IDTIENDA INT,
ORDEN INT,
USRCREA VARCHAR(45),
FCHCREA DATETIME,
USRMOD VARCHAR(45),
FCHMOD DATETIME,
FLGELI CHAR(1)
)

CREATE TABLE TPERFIL_USUARIO(
IDREGISTRO CHAR(18),
IDUSUARIO INT,
IDPERFIL INT,
USRCREA VARCHAR(45),
FCHCREA DATETIME,
USRMOD VARCHAR(45),
FCHMOD DATETIME,
FLGELI CHAR(1)
)

/*
----POR AGREGAR
Modulo inventarios
Modulo de cajas
Modulo de RRHH
*/