USE FINADB
GO
CREATE TABLE TTABLA(
CODTABLA	int PRIMARY KEY IDENTITY(1000,1),
DETALLE	varchar(100),
USUARIO_CREA varchar(50),
USUARIO_MOD varchar(50),
FECHA_CREA DATE,
FECHA_MOD DATE,
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TTABLADETALLE(
CODTABLA	int,
DETALLE	varchar(50),
TABLA	varchar(50)
)
GO
-- TESTADO, TUME, TOPERACION


CREATE TABLE TGRUPO(
CODGRUPO	int PRIMARY KEY,
DETALLE	varchar(100),
DIARETIRO	int,
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TTIENDA(
CODTIENDA	INT PRIMARY KEY,
NOMBRE	varchar(100),
DIRECCION	varchar(100),
DEPARTAMENTO	varchar(50),
PROVINCIA	varchar(50),
DISTRITO	varchar(50),
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TALMACEN(
CODALMACEN	INT PRIMARY KEY,
DESCRIPCION	varchar(50),
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TUSUARIO(
CODUSUARIO	int PRIMARY KEY IDENTITY(1,1),
TIPO	varchar(50),
USUARIO	varchar(50),
CLAVE	varchar(50),
EMAIL	varchar(50),
NOMBRE	varchar(100),
APELLIDOS	varchar(100),
FECHANAC	DATE,
DNI	varchar(10),
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TPROVEEDOR(
RUC	int PRIMARY KEY,
RAZONSOCIAL	varchar(100),
DIRECCION	varchar(100),
TELEFONO	varchar(100),
RUBRO	varchar(50),
FLGELIMINADO CHAR(1)
)
GO

CREATE TABLE TPRODUCTO(
CODPROD	int PRIMARY KEY IDENTITY(1000,1),
CODGRUPO	INT,
RUC	INT,
EAN13	varchar(15),
DESCRIPCION	varchar(100),
PRECIO	float,
FLGELIMINADO CHAR(1)
CONSTRAINT  FK_RUC_PRODUCTO FOREIGN KEY(RUC) REFERENCES TPROVEEDOR(RUC),
CONSTRAINT  FK_CODGRUPO_PRODUCTO FOREIGN KEY(CODGRUPO) REFERENCES TGRUPO(CODGRUPO)
)
GO

CREATE TABLE TMOVIMIENTO(
CODMOVIMIENTO int PRIMARY KEY IDENTITY(5000000,1),
CODUSUARIO	int,
MONTOTOTAL float,
FECHA_MOVIMIENTO date,
USUARIO_CREA varchar(50),
USUARIO_MOD varchar(50),
FECHA_CREA DATE,
FECHA_MOD DATE,
FLGELIMINADO CHAR(1)
CONSTRAINT  FK_CODUSUARIO_MOV FOREIGN KEY(CODUSUARIO) REFERENCES TUSUARIO(CODUSUARIO)
)
GO

CREATE TABLE TDETMOVIMIENTO(
CODMOVIMIENTO int,
CODPROD	INT,
CANTIDAD	float,
FECHAVEN	date,
TIPO_OPERACION VARCHAR(50),
USUARIO_CREA varchar(50),
USUARIO_MOD varchar(50),
FECHA_CREA DATE,
FECHA_MOD DATE,
FLGELIMINADO CHAR(1)
CONSTRAINT  FK_CODINGRESO_DETMOV FOREIGN KEY(CODMOVIMIENTO) REFERENCES TMOVIMIENTO(CODMOVIMIENTO),
CONSTRAINT  FK_CODPROD_DETMOV FOREIGN KEY(CODPROD) REFERENCES TPRODUCTO(CODPROD)
)
GO
CREATE TABLE TDEPOSITO(
CODDEPOSITO INT PRIMARY KEY IDENTITY(1,1),
CODPROD	INT,
CODALMACEN	INT,
CODTIENDA	INT,
CANTIDAD	float,
FECHA_VEN	date,
FECHA_RET	date,
USUARIO_CREA varchar(50),
USUARIO_MOD varchar(50),
FECHA_CREA DATE,
FECHA_MOD DATE,
FLGELIMINADO CHAR(1)
CONSTRAINT  FK_CODPROD_TDEPOSITO FOREIGN KEY(CODPROD) REFERENCES TPRODUCTO(CODPROD),
CONSTRAINT  FK_CODALMACEN_TDEPOSITO FOREIGN KEY(CODALMACEN) REFERENCES TALMACEN(CODALMACEN),
CONSTRAINT  FK_CODTIENDA_TDEPOSITO FOREIGN KEY(CODTIENDA) REFERENCES TTIENDA(CODTIENDA)
)
GO

/*
----POR AGREGAR
Modulo inventarios
Modulo de cajas
Modulo de RRHH
*/